3.9 is not installed; attempting download0.05s
worker_info

Worker information

0.14s0.01s0.00s0.01s
system_info

Build system information

0.01s0.01s0.71s0.27s0.05s0.00s0.04s0.00s0.01s0.01s0.01s0.01s0.01s0.00s0.00s0.02s0.00s0.01s0.29s0.00s0.00s0.00s0.01s0.00s0.09s0.00s0.91s0.00s0.00s6.03s0.00s2.78s0.00s2.13s
docker_mtu_and_registry_mirrors
resolvconf

Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.9.tar.bz2

0.38s$ curl -sSf --retry 5 -o python-3.9.tar.bz2 ${archive_url}

10.49s$ sudo tar xjf python-3.9.tar.bz2 --directory /

0.00s
git.checkout

0.75s$ git clone --depth=50 --branch=main https://github.com/engineersakibcse47/FaceRecognition.git engineersakibcse47/FaceRecognition

0.01s0.01s$ source ~/virtualenv/python3.9/bin/activate

$ python --version

Python 3.9.2

$ pip --version

pip 21.3.1 from /home/travis/virtualenv/python3.9.2/lib/python3.9/site-packages/pip (python 3.9)
install

1.51s$ pip install pybuilder

11.77s$ pyb

PyBuilder version 0.13.3

Build started at 2022-01-15 15:01:19

------------------------------------------------------------

[INFO]  Building FaceRecognition version 1.0.dev0

[INFO]  Executing build in /home/travis/build/engineersakibcse47/FaceRecognition

[INFO]  Going to execute task publish

[INFO]  Processing plugin packages 'flake8~=4.0' to be installed with {'upgrade': True}

[INFO]  Processing plugin packages 'pypandoc~=1.4' to be installed with {'upgrade': True}

[INFO]  Processing plugin packages 'setuptools>=38.6.0' to be installed with {'upgrade': True}

[INFO]  Processing plugin packages 'twine>=1.15.0' to be installed with {'upgrade': True}

[INFO]  Processing plugin packages 'unittest-xml-reporting~=3.0.4' to be installed with {'upgrade': True}

[INFO]  Processing plugin packages 'wheel>=0.34.0' to be installed with {'upgrade': True}

[INFO]  Creating target 'build' VEnv in '/home/travis/build/engineersakibcse47/FaceRecognition/target/venv/build/cpython-3.9.15.final.0'

[INFO]  Creating target 'test' VEnv in '/home/travis/build/engineersakibcse47/FaceRecognition/target/venv/test/cpython-3.9.15.final.0'

[INFO]  Requested coverage for tasks: pybuilder.plugins.python.unittest_plugin:run_unit_tests

[INFO]  Running unit tests

[INFO]  Executing unit tests from Python modules in /home/travis/build/engineersakibcse47/FaceRecognition/src/unittest/python

[INFO]  No unit tests executed.

[INFO]  All unit tests passed.

[INFO]  Building distribution in /home/travis/build/engineersakibcse47/FaceRecognition/target/dist/Face Recognition-1.0.dev0

[INFO]  Copying scripts to /home/travis/build/engineersakibcse47/FaceRecognition/target/dist/Face Recognition-1.0.dev0/scripts

[INFO]  Writing setup.py as /home/travis/build/engineersakibcse47/FaceRecognition/target/dist/Face Recognition-1.0.dev0/setup.py

[INFO]  Building binary distribution in /home/travis/build/engineersakibcse47/FaceRecognition/target/dist/Face Recognition-1.0.dev0

[INFO]  Running Twine check for generated artifacts

------------------------------------------------------------

BUILD SUCCESSFUL

------------------------------------------------------------

Build Summary

             Project: Face Recognition

             Version: 1.0.dev0

      Base directory: /home/travis/build/engineersakibcse47/FaceRecognition

        Environments: ci

               Tasks: prepare [9107 ms] compile_sources [0 ms] run_unit_tests [298 ms] package [2 ms] run_integration_tests [0 ms] verify [0 ms] publish [1023 ms]

Build finished at 2022-11-25 10:43:03

Build took 11 seconds (116557 ms)

The command "pyb" exited with 0.

Done. Your build exited with 0.
